[package]
name = "mobius-ui"
version.workspace = true
edition.workspace = true

[dependencies]
dioxus = { workspace = true, features = ["router"] }
dioxus-icons = { workspace = true }
dioxus-primitives = { workspace = true }
futures-util = { workspace = true }
mobius-api = { workspace = true }
mobius-domain = { workspace = true }
pulldown-cmark = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true, features = ["formatting", "macros"] }
web-sys = { workspace = true, features = ["KeyboardEvent"] }

[build-dependencies]
sha2 = { workspace = true }

[dev-dependencies]
dioxus-ssr = { workspace = true }

[features]
web = ["dioxus/web", "dioxus-primitives/web"]
server = ["dioxus/server", "mobius-api/server"]
